fix linter warnings

diff --git a/launchers/.local/bin/mybrain b/launchers/.local/bin/mybrain
--- a/launchers/.local/bin/mybrain
+++ b/launchers/.local/bin/mybrain
@@ -40,9 +40,9 @@ parameters='[-v] [-d] [-s]'
 # - terminal in which to launch wiki server
 terminal='alacritty'
 terminal_cmd_array=(
-    'alacritty'
-        '-t' 'launcher_tiddlywiki'
-        '-e'
+	'alacritty'
+	'-t' 'launcher_tiddlywiki'
+	'-e'
 )
 terminal_cmd="${terminal_cmd_array[*]}"
 # - port for client-server communication
@@ -77,10 +77,10 @@ client_cmd="${client_cmd//%URL%/$url}"
 terminal_grep="$terminal_cmd $server_cmd"
 # - matching string for finding server command in ps output
 wiki_exe_grep_array=(
-    'node'
-        "$(which tiddlywiki)"
-        "$wiki_db_dir"
-        "--listen port=$port"
+	'node'
+	"$(which tiddlywiki)"
+	"$wiki_db_dir"
+	"--listen port=$port"
 )
 wiki_exe_grep="${wiki_exe_grep_array[*]}"
 # - all grep matches to grep for detecting a running wiki server
@@ -89,18 +89,18 @@ grep_matchers=("$terminal_grep" "$wiki_exe_grep")
 show_cmd=false
 # - whether connected to a terminal
 connected_to_terminal=false
-unset -v client_cmd_template  server_cmd_template  terminal_cmd_array
-unset -v terminal_grep  url  url_template  wiki_exe_grep  wiki_exe_grep_array
+unset -v client_cmd_template server_cmd_template terminal_cmd_array
+unset -v terminal_grep url url_template wiki_exe_grep wiki_exe_grep_array
 # tools whose absence will cause a fatal error
 required_tools=(
-    $terminal
-    $browser
-    $server_exe
-    getopt
-    grep
-    dn-tk-info
-    dn-tk-error
-)    # }}}1
+	"$terminal"
+	"$browser"
+	"$server_exe"
+	getopt
+	grep
+	dn-tk-info
+	dn-tk-error
+) # }}}1
 
 # PROCEDURES
 
@@ -108,8 +108,8 @@ required_tools=(
 #   params: nil
 #   prints: nil
 #   return: nil
-display_usage () {
-cat << _USAGE
+display_usage() {
+	cat <<_USAGE
 ${self}: start personal wiki server and browser client
 
 Starts the wiki server ($server_exe) in a terminal
@@ -133,33 +133,45 @@ _USAGE
 #   params: all command line parameters
 #   prints: feedback
 #   return: nil
-#   note:   after execution variable ARGS contains
-#           remaining command line args (after options removed)
-process_options () {
-    # read the command line options
-    local OPTIONS="$(                            \
-        getopt                                   \
-            --options hvds                       \
-            --long    showcmd,help,verbose,debug \
-            --name    "${BASH_SOURCE[0]}"        \
-            -- "${@}"                            \
-    )"
-    [[ ${?} -eq 0 ]] || {
-        echo 'Invalid command line options' 1>&2
-        exit 1
-    }
-    eval set -- "${OPTIONS}"
-    while true ; do
-        case "${1}" in
-        -s | --showcmd ) show_cmd=true  ; shift 1 ;;
-        -h | --help    ) display_usage  ; exit 0  ;;
-        -v | --verbose ) set -o verbose ; shift 1 ;;
-        -d | --debug   ) set -o xtrace  ; shift 1 ;;
-        --             ) shift ; break ;;
-        *              ) break ;;
-        esac
-    done
-    ARGS="${@}"  # remaining arguments
+process_options() {
+	# read the command line options
+	local OPTIONS
+	if ! OPTIONS="$(
+		getopt \
+			--options hvds \
+			--long showcmd,help,verbose,debug \
+			--name "${BASH_SOURCE[0]}" \
+			-- "${@}"
+	)"; then
+		# getopt displays errors
+		exit 1
+	fi
+	eval set -- "${OPTIONS}"
+	while true; do
+		case "${1}" in
+		-s | --showcmd)
+			show_cmd=true
+			shift 1
+			;;
+		-h | --help)
+			display_usage
+			exit 0
+			;;
+		-v | --verbose)
+			set -o verbose
+			shift 1
+			;;
+		-d | --debug)
+			set -o xtrace
+			shift 1
+			;;
+		--)
+			shift
+			break
+			;;
+		*) break ;;
+		esac
+	done
 }
 
 # join_by() -> void    {{{1
@@ -167,12 +179,12 @@ process_options () {
 #           2+ - items to be joined
 #   prints: string containing joined items
 #   return: nil
-function join_by () {
-    local delimiter=${1:-''}
-    shift
-    local items=${1:-''}
-    shift
-    printf %s "$items" "${@/#/$delimiter}"
+function join_by() {
+	local delimiter=${1:-''}
+	shift
+	local items=${1:-''}
+	shift
+	printf %s "$items" "${@/#/$delimiter}"
 }
 
 # determine_terminal_connection() -> bool   {{{1
@@ -183,19 +195,19 @@ function join_by () {
 # displays: nil
 #  returns: nil
 function determine_terminal_connection {
-    # on KDE Plasma 5 the '-t -p' test used below does not work,
-    # so as temporary workaround brute force a false result
-    if [[ "${XDG_CURRENT_DESKTOP:-}" = 'KDE' ]] ; then
-        connected_to_terminal=false
-        return
-    fi
+	# on KDE Plasma 5 the '-t -p' test used below does not work,
+	# so as temporary workaround brute force a false result
+	if [[ "${XDG_CURRENT_DESKTOP:-}" = 'KDE' ]]; then
+		connected_to_terminal=false
+		return
+	fi
 
-    # '-t 0' means stdin is open and refers to a terminal
-    # '-p /dev/stdin' means stdin exists and is a pipe (socket)
-    local interactive=false fd=0
-    [[ -t "$fd" || -p /dev/stdin ]] && interactive=true
-    # set connection flag
-    connected_to_terminal=$interactive
+	# '-t 0' means stdin is open and refers to a terminal
+	# '-p /dev/stdin' means stdin exists and is a pipe (socket)
+	local interactive=false fd=0
+	[[ -t "$fd" || -p /dev/stdin ]] && interactive=true
+	# set connection flag
+	connected_to_terminal=$interactive
 }
 
 # feedback($msg_type, $msg1[, ...]) -> void    {{{1
@@ -211,41 +223,43 @@ function determine_terminal_connection {
 #     note: the gui dialog displays the first message as a header, so it
 #           should be a summary of the message
 function feedback {
-    # param 1 = $msg_type
-    local msg_type
-    msg_type="$1"
-    shift
-    # param 2+ = $msg, ...
-    local -a msgs
-    while [[ -n "${1+x}" ]] ; do
-        msgs+=("$1")
-        shift
-    done
-    # print messages if connected to a terminal
-    if $connected_to_terminal ; then
-        local output
-        for msg in "${msgs[@]}" ; do
-            output="$self:"
-            [[ "x$msg_type" == 'xfatal' ]] && output+=' fatal:'
-            output+=" $msg"
-            case $msg_type in
-                fatal) echo "$output" > /dev/stderr ;;
-                info ) echo "$output" ;;
-                *    ) echo "Invalid message type '$msg_type'" > /dev/stderr
-                       exit ;;
-            esac
-        done
-        return
-    fi
-    # display in dialog box if not connected to a terminal
-    caption="${msgs[0]}"
-    msgs=("${msgs[@]:1}")
-    detail="$(join_by '\n' "${msgs[@]}")"
-    if [[ "x$msg_type" == 'xfatal' ]] ; then
-        dn-tk-error --title "$self" --caption "$caption" --detail "$detail"
-    else
-        dn-tk-info --title "$self" --caption "$caption" --detail "$detail"
-    fi
+	# param 1 = $msg_type
+	local msg_type
+	msg_type="$1"
+	shift
+	# param 2+ = $msg, ...
+	local -a msgs
+	while [[ -n "${1+x}" ]]; do
+		msgs+=("$1")
+		shift
+	done
+	# print messages if connected to a terminal
+	if $connected_to_terminal; then
+		local output
+		for msg in "${msgs[@]}"; do
+			output="$self:"
+			[[ "$msg_type" == 'fatal' ]] && output+=' fatal:'
+			output+=" $msg"
+			case $msg_type in
+			fatal) echo "$output" >/dev/stderr ;;
+			info) echo "$output" ;;
+			*)
+				echo "Invalid message type '$msg_type'" >/dev/stderr
+				exit
+				;;
+			esac
+		done
+		return
+	fi
+	# display in dialog box if not connected to a terminal
+	caption="${msgs[0]}"
+	msgs=("${msgs[@]:1}")
+	detail="$(join_by '\n' "${msgs[@]}")"
+	if [[ "$msg_type" == 'fatal' ]]; then
+		dn-tk-error --title "$self" --caption "$caption" --detail "$detail"
+	else
+		dn-tk-info --title "$self" --caption "$caption" --detail "$detail"
+	fi
 }
 
 # fb_fatal($msg1[, ...]) -> void    {{{1
@@ -256,8 +270,8 @@ function feedback {
 # displays: notification message if not connected to terminal
 #  returns: nil
 function fb_fatal {
-    feedback 'fatal' "$@"
-    exit
+	feedback 'fatal' "$@"
+	exit
 }
 
 # fb_info($msg1[, ...]) -> void    {{{1
@@ -268,7 +282,7 @@ function fb_fatal {
 # displays: notification message if not connected to terminal
 #  returns: nil
 function fb_info {
-    feedback 'info' "$@"
+	feedback 'info' "$@"
 }
 
 # fb_wait_for_server_start() -> void    {{{1
@@ -280,19 +294,19 @@ function fb_info {
 #           if not connected to terminal
 #  returns: nil
 function fb_wait_for_server_start {
-    local msg_term
-    msg_term='When TiddlyWiki server is running, '
-    msg_term+='press any button to open client'
-    if $connected_to_terminal ; then
-        read -r -s -n 1 -p "$self: $msg_term"
-        echo ''
-    else
-        sleep 1  # ensure server terminal has opened so dlg gets focus
-        fb_info "Waiting for $server server" \
-                "When $server server is running, " \
-                "press [OK] to open client in $browser"
-    fi
-}    # }}}1
+	local msg_term
+	msg_term='When TiddlyWiki server is running, '
+	msg_term+='press any button to open client'
+	if $connected_to_terminal; then
+		read -r -s -n 1 -p "$self: $msg_term"
+		echo ''
+	else
+		sleep 1 # ensure server terminal has opened so dlg gets focus
+		fb_info "Waiting for $server server" \
+			"When $server server is running, " \
+			"press [OK] to open client in $browser"
+	fi
+} # }}}1
 
 # MAIN
 
@@ -303,49 +317,48 @@ determine_terminal_connection
 
 # check for required tools    {{{1
 missing=()
-for tool in "${required_tools[@]}" ; do
-    command -v "${tool}" &>/dev/null || missing+=("${tool}")
+for tool in "${required_tools[@]}"; do
+	command -v "${tool}" &>/dev/null || missing+=("${tool}")
 done
-[[ ${#missing[@]} -eq 0 ]] \
-    || fb_fatal "Need required tools to run" \
-                "Cannot locate: $(join_by ', ' "${missing[@]}")"
+[[ ${#missing[@]} -eq 0 ]] ||
+	fb_fatal "Need required tools to run" \
+		"Cannot locate: $(join_by ', ' "${missing[@]}")"
 unset missing tools required_tools
 
 # process command line options    {{{1
-# - results in $ARGS holding remaining non-option command line arguments
 process_options "${@}"
-unset port  server_exe  terminal
+unset port server_exe terminal
 
 # check that wiki database directory is valid    {{{1
-if [ ! -d "$wiki_db_dir" ] ; then
-    fb_fatal 'Need wiki directory to run' \
-             "Cannot locate wiki database directory: $wiki_db_dir"
+if [ ! -d "$wiki_db_dir" ]; then
+	fb_fatal 'Need wiki directory to run' \
+		"Cannot locate wiki database directory: $wiki_db_dir"
 fi
 unset -v wiki_db_dir
 
 # check server is not already running    {{{1
 # - use ps, not pgrep, because pgrep only checks executable name,
 #   not the entire command (so suppress shellcheck warning SC2009)
-for matcher in "${grep_matchers[@]}" ; do
-    $show_cmd && echo "if ps -e -o cmd | grep \"\^$matcher\$\" ; then"
-    # shellcheck disable=SC2009
-    if ps -e -o cmd | grep "^$matcher$" > /dev/null 2>&1 ; then
-        fb_fatal "$server is already running" \
-                 "Found process matching: '$matcher'"
-    fi
+for matcher in "${grep_matchers[@]}"; do
+	$show_cmd && echo "if ps -e -o cmd | grep \"\^$matcher\$\" ; then"
+	# shellcheck disable=SC2009
+	if ps -e -o cmd | grep "^$matcher$" >/dev/null 2>&1; then
+		fb_fatal "$server is already running" \
+			"Found process matching: '$matcher'"
+	fi
 done
 unset -v grep_matchers
 
 # start server in terminal    {{{1
 $show_cmd && echo "$terminal_cmd $server_cmd &"
-$terminal_cmd $server_cmd &
+$terminal_cmd "$server_cmd" &
 fb_wait_for_server_start
-unset -v browser  connected_to_terminal  server  server_cmd  terminal_cmd
+unset -v browser connected_to_terminal server server_cmd terminal_cmd
 
 # start client in browser    {{{1
 $show_cmd && echo "$client_cmd > /dev/null 2>&1 &"
-$client_cmd > /dev/null 2>&1 &
-unset -v client_cmd  show_cmd
+$client_cmd >/dev/null 2>&1 &
+unset -v client_cmd show_cmd
 # }}}1
 
 # vim:foldmethod=marker:
diff --git a/launchers/.local/bin/syncthing-launcher b/launchers/.local/bin/syncthing-launcher
--- a/launchers/.local/bin/syncthing-launcher
+++ b/launchers/.local/bin/syncthing-launcher
@@ -39,8 +39,8 @@ parameters='[-v] [-d] [-s]'
 # - terminal in which to launch syncthing server
 terminal='alacritty'
 terminal_opts_template_array=(
-    '-t' 'launcher_syncthing'
-    '-e'
+	'-t' 'launcher_syncthing'
+	'-e'
 )
 terminal_opts_template="${terminal_opts_template_array[*]}"
 # - command to invoke terminal
@@ -48,8 +48,6 @@ terminal_cmd_template="$terminal $terminal_opts_template"
 # - perform variable substitutions
 terminal_cmd="$terminal_cmd_template"
 terminal_cmd="${terminal_cmd//%TERMINAL%/$terminal}"
-# - port for client-server communication
-port=10744
 # - syncthing executable name
 server='Syncthing'
 server_exe='syncthing'
@@ -65,16 +63,16 @@ grep_matcher="$terminal_cmd $server_cmd"
 show_cmd=false
 # - whether connected to a terminal
 connected_to_terminal=false
-unset -v server_cmd_template           terminal_cmd_template   \
-         terminal_opts_template_array  terminal_opts_template
+unset -v server_cmd_template terminal_cmd_template \
+	terminal_opts_template_array terminal_opts_template
 # tools whose absence will cause a fatal error
 required_tools=(
-    $terminal
-    $server_exe
-    getopt
-    grep
-    dn-tk-error
-)    # }}}1
+	"$terminal"
+	"$server_exe"
+	getopt
+	grep
+	dn-tk-error
+) # }}}1
 
 # PROCEDURES
 
@@ -82,8 +80,8 @@ required_tools=(
 #   params: nil
 #   prints: nil
 #   return: nil
-display_usage () {
-cat << _USAGE
+display_usage() {
+	cat <<_USAGE
 ${self}: start syncthing server and browser client
 
 Starts the $server server ($server_exe) in a terminal
@@ -106,33 +104,45 @@ _USAGE
 #   params: all command line parameters
 #   prints: feedback
 #   return: nil
-#   note:   after execution variable ARGS contains
-#           remaining command line args (after options removed)
-process_options () {
-    # read the command line options
-    local OPTIONS="$(                            \
-        getopt                                   \
-            --options hvds                       \
-            --long    showcmd,help,verbose,debug \
-            --name    "${BASH_SOURCE[0]}"        \
-            -- "${@}"                            \
-    )"
-    [[ ${?} -eq 0 ]] || {
-        echo 'Invalid command line options' 1>&2
-        exit 1
-    }
-    eval set -- "${OPTIONS}"
-    while true ; do
-        case "${1}" in
-        -s | --showcmd ) show_cmd=true  ; shift 1 ;;
-        -h | --help    ) display_usage  ; exit 0  ;;
-        -v | --verbose ) set -o verbose ; shift 1 ;;
-        -d | --debug   ) set -o xtrace  ; shift 1 ;;
-        --             ) shift ; break ;;
-        *              ) break ;;
-        esac
-    done
-    ARGS="${@}"  # remaining arguments
+process_options() {
+	# read the command line options
+	local OPTIONS
+	if ! OPTIONS="$(
+		getopt \
+			--options hvds \
+			--long showcmd,help,verbose,debug \
+			--name "${BASH_SOURCE[0]}" \
+			-- "${@}"
+	)"; then
+		# getopt displays error
+		exit 1
+	fi
+	eval set -- "${OPTIONS}"
+	while true; do
+		case "${1}" in
+		-s | --showcmd)
+			show_cmd=true
+			shift 1
+			;;
+		-h | --help)
+			display_usage
+			exit 0
+			;;
+		-v | --verbose)
+			set -o verbose
+			shift 1
+			;;
+		-d | --debug)
+			set -o xtrace
+			shift 1
+			;;
+		--)
+			shift
+			break
+			;;
+		*) break ;;
+		esac
+	done
 }
 
 # join_by() -> void    {{{1
@@ -140,12 +150,12 @@ process_options () {
 #           2+ - items to be joined
 #   prints: string containing joined items
 #   return: nil
-function join_by () {
-    local d=$1
-    shift
-    local f=$1
-    shift
-    printf %s "$f" "${@/#/$d}"
+function join_by() {
+	local d=$1
+	shift
+	local f=$1
+	shift
+	printf %s "$f" "${@/#/$d}"
 }
 
 # determine_terminal_connection() -> bool   {{{1
@@ -156,19 +166,19 @@ function join_by () {
 # displays: nil
 #  returns: nil
 function determine_terminal_connection {
-    # on KDE Plasma 5 the '-t -p' test used below does not work,
-    # so as temporary workaround brute force a false result
-    if [[ "${XDG_CURRENT_DESKTOP:-}" = 'KDE' ]] ; then
-        connected_to_terminal=false
-        return
-    fi
+	# on KDE Plasma 5 the '-t -p' test used below does not work,
+	# so as temporary workaround brute force a false result
+	if [[ "${XDG_CURRENT_DESKTOP:-}" = 'KDE' ]]; then
+		connected_to_terminal=false
+		return
+	fi
 
-    # '-t 0' means stdin is open and refers to a terminal
-    # '-p /dev/stdin' means stdin exists and is a pipe (socket)
-    local interactive=false fd=0
-    [[ -t "$fd" || -p /dev/stdin ]] && interactive=true
-    # set connection flag
-    connected_to_terminal=$interactive
+	# '-t 0' means stdin is open and refers to a terminal
+	# '-p /dev/stdin' means stdin exists and is a pipe (socket)
+	local interactive=false fd=0
+	[[ -t "$fd" || -p /dev/stdin ]] && interactive=true
+	# set connection flag
+	connected_to_terminal=$interactive
 }
 
 # fatal($msg1[, ...]) -> void    {{{1
@@ -183,28 +193,28 @@ function determine_terminal_connection {
 #     note: the gui dialog displays the first message as a header, so it
 #           should be a summary of the message
 function fatal {
-    # param 1+ = $msg, ...
-    local -a msgs
-    while [[ -n "${1+x}" ]] ; do
-        msgs+=("$1")
-        shift
-    done
-    # print messages if connected to a terminal
-    if $connected_to_terminal ; then
-        local output
-        for msg in "${msgs[@]}" ; do
-            output="$self: fatal:"
-            output+=" $msg"
-            echo "$output" > /dev/stderr
-        done
-        return
-    fi
-    # display in dialog box if not connected to a terminal
-    caption="${msgs[0]}"
-    msgs=("${msgs[@]:1}")
-    detail="$(join_by '\n' "${msgs[@]}")"
-    dn-tk-error --title "$self" --caption "$caption" --detail "$detail"
-}    #}}}1
+	# param 1+ = $msg, ...
+	local -a msgs
+	while [[ -n "${1+x}" ]]; do
+		msgs+=("$1")
+		shift
+	done
+	# print messages if connected to a terminal
+	if $connected_to_terminal; then
+		local output
+		for msg in "${msgs[@]}"; do
+			output="$self: fatal:"
+			output+=" $msg"
+			echo "$output" >/dev/stderr
+		done
+		return
+	fi
+	# display in dialog box if not connected to a terminal
+	caption="${msgs[0]}"
+	msgs=("${msgs[@]:1}")
+	detail="$(join_by '\n' "${msgs[@]}")"
+	dn-tk-error --title "$self" --caption "$caption" --detail "$detail"
+} #}}}1
 
 # MAIN
 
@@ -215,34 +225,33 @@ determine_terminal_connection
 
 # check for required tools    {{{1
 missing=()
-for tool in "${required_tools[@]}" ; do
-    command -v "${tool}" &>/dev/null || missing+=("${tool}")
+for tool in "${required_tools[@]}"; do
+	command -v "${tool}" &>/dev/null || missing+=("${tool}")
 done
-[[ ${#missing[@]} -eq 0 ]] \
-    || fatal "Need required tools to run" \
-             "Cannot locate: $(join_by ', ' "${missing[@]}")"
+[[ ${#missing[@]} -eq 0 ]] ||
+	fatal "Need required tools to run" \
+		"Cannot locate: $(join_by ', ' "${missing[@]}")"
 unset missing tools required_tools
 
 # process command line options    {{{1
-# - results in $ARGS holding remaining non-option command line arguments
 process_options "${@}"
-unset server_exe  terminal
+unset server_exe terminal
 
 # check server is not already running    {{{1
 # - use ps, not pgrep, because pgrep only checks executable name,
 #   not the entire command (so suppress shellcheck warning SC2009)
 $show_cmd && echo "if ps -e -o cmd | grep \"\^$grep_matcher\$\" ; then"
 # shellcheck disable=SC2009
-if ps -e -o cmd | grep "^$grep_matcher$" > /dev/null 2>&1 ; then
-    fatal "$server is already running" \
-          "Found process running: '$grep_matcher'"
+if ps -e -o cmd | grep "^$grep_matcher$" >/dev/null 2>&1; then
+	fatal "$server is already running" \
+		"Found process running: '$grep_matcher'"
 fi
-unset -v connected_to_terminal  grep_matcher  server
+unset -v connected_to_terminal grep_matcher server
 
 # start server in terminal    {{{1
 $show_cmd && echo "$terminal_cmd $server_cmd &"
-$terminal_cmd $server_cmd &
-unset -v server_cmd  show_cmd  terminal_cmd
+$terminal_cmd "$server_cmd" &
+unset -v server_cmd show_cmd terminal_cmd
 # }}}1
 
 # vim:foldmethod=marker:
