fix prompt text

diff --git a/launchers/.local/bin/pil4e b/launchers/.local/bin/pil4e
--- a/launchers/.local/bin/pil4e
+++ b/launchers/.local/bin/pil4e
@@ -6,7 +6,6 @@
 #          with nanoc web server
 # Created: 2021-08-19
 
-
 # ERROR HANDLING    {{{1
 
 # Exit on error. Append "|| true" if you expect an error.
@@ -48,9 +47,9 @@ terminal='alacritty'
 # - terminal options
 #   '-qwindowtitle' 'launcher_pil4e'
 terminal_opts_template_array=(
-    '-t' 'launcher_pil4e'
-    '--working-directory' '%SITE_DIR%'
-    '-e'
+	'-t' 'launcher_pil4e'
+	'--working-directory' '%SITE_DIR%'
+	'-e'
 )
 terminal_opts_template="${terminal_opts_template_array[*]}"
 # - command to invoke terminal
@@ -65,10 +64,10 @@ server_exe='nanoc'
 port='3000'
 # - server command option used if adsf-live gem package is installed
 live=''
-if command -v gem &>/dev/null ; then
-    installed="$(sudo gem list --local --installed --exact --quiet adsf-live)"
-    # note space in $live to separate options on command line
-    [[ "$installed" = 'true' ]] && live=' --live-reload'
+if command -v gem &>/dev/null; then
+	installed="$(sudo gem list --local --installed --exact --quiet adsf-live)"
+	# note space in $live to separate options on command line
+	[[ "$installed" = 'true' ]] && live=' --live-reload'
 fi
 server_cmd_template='%SERVER_EXE% view --port=%PORT%%LIVE%'
 # - perform variable substitutions
@@ -96,20 +95,20 @@ grep_matcher="$terminal_cmd $server_cmd"
 show_cmd=false
 # - whether connected to a terminal
 connected_to_terminal=false
-unset -v client_cmd_template     server_cmd_template           \
-         terminal_cmd_template   terminal_opts_template_array  \
-         terminal_opts_template  url                           \
-         url_template
+unset -v client_cmd_template server_cmd_template \
+	terminal_cmd_template terminal_opts_template_array \
+	terminal_opts_template url \
+	url_template
 # tools whose absence will cause a fatal error
 required_tools=(
-    $terminal
-    $browser
-    $server_exe
-    getopt
-    grep
-    dn-tk-info
-    dn-tk-error
-)    # }}}1
+	$terminal
+	$browser
+	$server_exe
+	getopt
+	grep
+	dn-tk-info
+	dn-tk-error
+) # }}}1
 
 # PROCEDURES
 
@@ -117,8 +116,8 @@ required_tools=(
 #   params: nil
 #   prints: nil
 #   return: nil
-display_usage () {
-cat << _USAGE
+display_usage() {
+	cat <<_USAGE
 ${self}: display "$site_name" with nanoc web server
 
 Launches a terminal ($terminal) in which the html server
@@ -149,31 +148,46 @@ _USAGE
 #   return: nil
 #   note:   after execution variable ARGS contains
 #           remaining command line args (after options removed)
-process_options () {
-    # read the command line options
-    local OPTIONS="$(                            \
-        getopt                                   \
-            --options hvds                       \
-            --long    showcmd,help,verbose,debug \
-            --name    "${BASH_SOURCE[0]}"        \
-            -- "${@}"                            \
-    )"
-    [[ ${?} -eq 0 ]] || {
-        echo 'Invalid command line options' 1>&2
-        exit 1
-    }
-    eval set -- "${OPTIONS}"
-    while true ; do
-        case "${1}" in
-        -s | --showcmd ) show_cmd=true  ; shift 1 ;;
-        -h | --help    ) display_usage  ; exit 0  ;;
-        -v | --verbose ) set -o verbose ; shift 1 ;;
-        -d | --debug   ) set -o xtrace  ; shift 1 ;;
-        --             ) shift ; break ;;
-        *              ) break ;;
-        esac
-    done
-    ARGS="${@}"  # remaining arguments
+process_options() {
+	# read the command line options
+	local OPTIONS="$(
+		getopt \
+			--options hvds \
+			--long showcmd,help,verbose,debug \
+			--name "${BASH_SOURCE[0]}" \
+			-- "${@}"
+	)"
+	[[ ${?} -eq 0 ]] || {
+		echo 'Invalid command line options' 1>&2
+		exit 1
+	}
+	eval set -- "${OPTIONS}"
+	while true; do
+		case "${1}" in
+		-s | --showcmd)
+			show_cmd=true
+			shift 1
+			;;
+		-h | --help)
+			display_usage
+			exit 0
+			;;
+		-v | --verbose)
+			set -o verbose
+			shift 1
+			;;
+		-d | --debug)
+			set -o xtrace
+			shift 1
+			;;
+		--)
+			shift
+			break
+			;;
+		*) break ;;
+		esac
+	done
+	ARGS="${@}" # remaining arguments
 }
 
 # join_by() -> void    {{{1
@@ -181,12 +195,12 @@ process_options () {
 #           2+ - items to be joined
 #   prints: string containing joined items
 #   return: nil
-function join_by () {
-    local d=$1
-    shift
-    local f=$1
-    shift
-    printf %s "$f" "${@/#/$d}"
+function join_by() {
+	local d=$1
+	shift
+	local f=$1
+	shift
+	printf %s "$f" "${@/#/$d}"
 }
 
 # determine_terminal_connection() -> bool   {{{1
@@ -197,19 +211,19 @@ function join_by () {
 # displays: nil
 #  returns: nil
 function determine_terminal_connection {
-    # on KDE Plasma 5 the '-t -p' test used below does not work,
-    # so as temporary workaround brute force a false result
-    if [[ "${XDG_CURRENT_DESKTOP:-}" = 'KDE' ]] ; then
-        connected_to_terminal=false
-        return
-    fi
+	# on KDE Plasma 5 the '-t -p' test used below does not work,
+	# so as temporary workaround brute force a false result
+	if [[ "${XDG_CURRENT_DESKTOP:-}" = 'KDE' ]]; then
+		connected_to_terminal=false
+		return
+	fi
 
-    # '-t 0' means stdin is open and refers to a terminal
-    # '-p /dev/stdin' means stdin exists and is a pipe (socket)
-    local interactive=false fd=0
-    [[ -t "$fd" || -p /dev/stdin ]] && interactive=true
-    # set connection flag
-    connected_to_terminal=$interactive
+	# '-t 0' means stdin is open and refers to a terminal
+	# '-p /dev/stdin' means stdin exists and is a pipe (socket)
+	local interactive=false fd=0
+	[[ -t "$fd" || -p /dev/stdin ]] && interactive=true
+	# set connection flag
+	connected_to_terminal=$interactive
 }
 
 # feedback($msg_type, $msg1[, ...]) -> void    {{{1
@@ -225,41 +239,43 @@ function determine_terminal_connection {
 #     note: the gui dialog displays the first message as a header, so it
 #           should be a summary of the message
 function feedback {
-    # param 1 = $msg_type
-    local msg_type
-    msg_type="$1"
-    shift
-    # param 2+ = $msg, ...
-    local -a msgs
-    while [[ -n "${1+x}" ]] ; do
-        msgs+=("$1")
-        shift
-    done
-    # print messages if connected to a terminal
-    if $connected_to_terminal ; then
-        local output
-        for msg in "${msgs[@]}" ; do
-            output="$self:"
-            [[ "x$msg_type" == 'xfatal' ]] && output+=' fatal:'
-            output+=" $msg"
-            case $msg_type in
-                fatal) echo "$output" > /dev/stderr ;;
-                info ) echo "$output" ;;
-                *    ) echo "Invalid message type '$msg_type'" > /dev/stderr
-                       exit ;;
-            esac
-        done
-        return
-    fi
-    # display in dialog box if not connected to a terminal
-    caption="${msgs[0]}"
-    msgs=("${msgs[@]:1}")
-    detail="$(join_by '\n' "${msgs[@]}")"
-    if [[ "x$msg_type" == 'xfatal' ]] ; then
-        dn-tk-error --title "$self" --caption "$caption" --detail "$detail"
-    else
-        dn-tk-info --title "$self" --caption "$caption" --detail "$detail"
-    fi
+	# param 1 = $msg_type
+	local msg_type
+	msg_type="$1"
+	shift
+	# param 2+ = $msg, ...
+	local -a msgs
+	while [[ -n "${1+x}" ]]; do
+		msgs+=("$1")
+		shift
+	done
+	# print messages if connected to a terminal
+	if $connected_to_terminal; then
+		local output
+		for msg in "${msgs[@]}"; do
+			output="$self:"
+			[[ "x$msg_type" == 'xfatal' ]] && output+=' fatal:'
+			output+=" $msg"
+			case $msg_type in
+			fatal) echo "$output" >/dev/stderr ;;
+			info) echo "$output" ;;
+			*)
+				echo "Invalid message type '$msg_type'" >/dev/stderr
+				exit
+				;;
+			esac
+		done
+		return
+	fi
+	# display in dialog box if not connected to a terminal
+	caption="${msgs[0]}"
+	msgs=("${msgs[@]:1}")
+	detail="$(join_by '\n' "${msgs[@]}")"
+	if [[ "x$msg_type" == 'xfatal' ]]; then
+		dn-tk-error --title "$self" --caption "$caption" --detail "$detail"
+	else
+		dn-tk-info --title "$self" --caption "$caption" --detail "$detail"
+	fi
 }
 
 # fb_fatal($msg1[, ...]) -> void    {{{1
@@ -270,8 +286,8 @@ function feedback {
 # displays: notification message if not connected to terminal
 #  returns: nil
 function fb_fatal {
-    feedback 'fatal' "$@"
-    exit
+	feedback 'fatal' "$@"
+	exit
 }
 
 # fb_info($msg1[, ...]) -> void    {{{1
@@ -282,7 +298,7 @@ function fb_fatal {
 # displays: notification message if not connected to terminal
 #  returns: nil
 function fb_info {
-    feedback 'info' "$@"
+	feedback 'info' "$@"
 }
 
 # fb_wait_for_server_start() -> void    {{{1
@@ -294,19 +310,19 @@ function fb_info {
 #           if not connected to terminal
 #  returns: nil
 function fb_wait_for_server_start {
-    local msg_term
-    msg_term='When TiddlyWiki server is running, '
-    msg_term+='press any button to open client'
-    if $connected_to_terminal ; then
-        read -r -s -n 1 -p "$self: $msg_term"
-        echo ''
-    else
-        sleep 1  # ensure server terminal has opened so dlg gets focus
-        fb_info "Waiting for $server server" \
-                "When $server server is running, " \
-                "press [OK] to open client in $browser"
-    fi
-}    # }}}1
+	local msg_term
+	msg_term='When the nanoc server is running, '
+	msg_term+='press any button to open client'
+	if $connected_to_terminal; then
+		read -r -s -n 1 -p "$self: $msg_term"
+		echo ''
+	else
+		sleep 1 # ensure server terminal has opened so dlg gets focus
+		fb_info "Waiting for $server server" \
+			"When $server server is running, " \
+			"press [OK] to open client in $browser"
+	fi
+} # }}}1
 
 # MAIN
 
@@ -317,23 +333,23 @@ determine_terminal_connection
 
 # check for required tools    {{{1
 missing=()
-for tool in "${required_tools[@]}" ; do
-    command -v "${tool}" &>/dev/null || missing+=("${tool}")
+for tool in "${required_tools[@]}"; do
+	command -v "${tool}" &>/dev/null || missing+=("${tool}")
 done
-[[ ${#missing[@]} -eq 0 ]] \
-    || fb_fatal "Need required tools to run" \
-                "Cannot locate: $(join_by ', ' "${missing[@]}")"
+[[ ${#missing[@]} -eq 0 ]] ||
+	fb_fatal "Need required tools to run" \
+		"Cannot locate: $(join_by ', ' "${missing[@]}")"
 unset missing tools required_tools
 
 # process command line options    {{{1
 # - results in $ARGS holding remaining non-option command line arguments
 process_options "${@}"
-unset port  server_exe  site_name  terminal
+unset port server_exe site_name terminal
 
 # check that site directory is valid    {{{1
-if [ ! -d "$site_dir" ] ; then
-    fb_fatal 'Need site directory to run' \
-             "Cannot locate site directory: $site_dir"
+if [ ! -d "$site_dir" ]; then
+	fb_fatal 'Need site directory to run' \
+		"Cannot locate site directory: $site_dir"
 fi
 unset -v site_dir
 
@@ -342,9 +358,9 @@ unset -v site_dir
 #   not the entire command (so suppress shellcheck warning SC2009)
 $show_cmd && echo "if ps -e -o cmd | grep \"\^$grep_matcher\$\" ; then"
 # shellcheck disable=SC2009
-if ps -e -o cmd | grep "^$grep_matcher$" > /dev/null 2>&1 ; then
-    fb_fatal "$server is already running" \
-             "Found process running: '$grep_matcher'"
+if ps -e -o cmd | grep "^$grep_matcher$" >/dev/null 2>&1; then
+	fb_fatal "$server is already running" \
+		"Found process running: '$grep_matcher'"
 fi
 unset -v grep_matcher
 
@@ -352,12 +368,12 @@ unset -v grep_matcher
 $show_cmd && echo "$terminal_cmd $server_cmd &"
 $terminal_cmd $server_cmd &
 fb_wait_for_server_start
-unset -v browser  connected_to_terminal  server  server_cmd  terminal_cmd
+unset -v browser connected_to_terminal server server_cmd terminal_cmd
 
 # start client in browser    {{{1
 $show_cmd && echo "$client_cmd > /dev/null 2>&1 &"
-$client_cmd > /dev/null 2>&1 &
-unset -v client_cmd  show_cmd
+$client_cmd >/dev/null 2>&1 &
+unset -v client_cmd show_cmd
 # }}}1
 
 # vim:foldmethod=marker:
