fix linter errors

diff --git a/i3/.local/bin/i3-my-background-set b/i3/.local/bin/i3-my-background-set
--- a/i3/.local/bin/i3-my-background-set
+++ b/i3/.local/bin/i3-my-background-set
@@ -20,26 +20,26 @@ set -o pipefail
 
 # VARIABLES    {{{1
 
-self="$(basename $0)"
+self="$(basename "$0")"
 required_tools=(
-    cut
-    feh
-    getopt
-    rev
-    seq
-    shuf
-    xrandr
+	cut
+	feh
+	getopt
+	rev
+	seq
+	shuf
+	xrandr
 )
 # hardware- and xrandr-dependent:
 # - resolutions for each monitor named by xrandr
-declare -A resolution=(     \
-    [DVI-D-0]="1920x1080"   \
-    [HDMI-A-0]="3440x1440"  \
+declare -A resolution=(
+	[DVI - D - 0]="1920x1080"
+	[HDMI - A - 0]="3440x1440"
 )
 # - directories containing wallpapers of given resolutions
-declare -A dir=(                                            \
-    [1920x1080]="/home/david/.config/wallpapers/1920x1080"  \
-    [3440x1440]="/home/david/.config/wallpapers/3440x1440"  \
+declare -A dir=(
+	[1920x1080]="/home/david/.config/wallpapers/1920x1080"
+	[3440x1440]="/home/david/.config/wallpapers/3440x1440"
 )
 # }}}1
 
@@ -50,8 +50,8 @@ declare -A dir=(                                            \
 #   params: nil
 #   prints: nil
 #   return: nil
-displayUsage () {
-cat << _USAGE
+displayUsage() {
+	cat <<_USAGE
 ${self}: set random background for each monitor
 
 This script relies on the following hardware setup:
@@ -83,30 +83,41 @@ _USAGE
 #   return: nil
 #   note:   after execution variable ARGS contains
 #           remaining command line args (after options removed)
-processOptions () {
-    # read the command line options
-    local OPTIONS="$(                     \
-        getopt                            \
-            --options hvd                 \
-            --long    help,verbose,debug  \
-            --name    "${BASH_SOURCE[0]}" \
-            -- "${@}"                     \
-    )"
-    [[ ${?} -eq 0 ]] || {
-        echo 'Invalid command line options' 1>&2
-        exit 1
-    }
-    eval set -- "${OPTIONS}"
-    while true ; do
-        case "${1}" in
-        -h | --help    ) displayUsage   ; exit 0  ;;
-        -v | --verbose ) set -o verbose ; shift 1 ;;
-        -d | --debug   ) set -o xtrace  ; shift 1 ;;
-        --             ) shift ; break ;;
-        *              ) break ;;
-        esac
-    done
-    ARGS="${@}"  # remaining arguments
+processOptions() {
+	# read the command line options
+	local OPTIONS
+	if ! OPTIONS="$(
+		getopt \
+			--options hvd \
+			--long help,verbose,debug \
+			--name "${BASH_SOURCE[0]}" \
+			-- "${@}"
+	)"; then
+		echo 'Invalid command line options' 1>&2
+		exit 1
+	fi
+	eval set -- "${OPTIONS}"
+	while true; do
+		case "${1}" in
+		-h | --help)
+			displayUsage
+			exit 0
+			;;
+		-v | --verbose)
+			set -o verbose
+			shift 1
+			;;
+		-d | --debug)
+			set -o xtrace
+			shift 1
+			;;
+		--)
+			shift
+			break
+			;;
+		*) break ;;
+		esac
+	done
 }
 # joinBy($delimiter, $item1, ...)    {{{1
 # Join items
@@ -114,21 +125,21 @@ processOptions () {
 #           2+ - items to be joined
 #   prints: string containing joined items
 #   return: nil
-function joinBy () {
-    local d=$1
-    shift
-    local f=$1
-    shift
-    printf %s "$f" "${@/#/$d}"
+function joinBy() {
+	local d=$1
+	shift
+	local f=$1
+	shift
+	printf %s "$f" "${@/#/$d}"
 }
 # abort($msg)    {{{1
 #     does: aborts script
 #   params: 1  - error message
 #   prints: error message to stderr
 #   return: nil
-function abort () {
-    echo "$1" > /dev/stderr
-    exit 1
+function abort() {
+	echo "$1" >/dev/stderr
+	exit 1
 }
 # }}}1
 
@@ -136,21 +147,21 @@ function abort () {
 
 # Check for required tools    {{{1
 missing=()
-for tool in "${required_tools[@]}" ; do
-    command -v "${tool}" &>/dev/null || missing+=("${tool}")
+for tool in "${required_tools[@]}"; do
+	command -v "${tool}" &>/dev/null || missing+=("${tool}")
 done
-[[ ${#missing[@]} -eq 0 ]] \
-    || abort "Can't run without: $(joinBy ', ' "${missing[@]}")"
-unset missing  tools  required_tools
+[[ ${#missing[@]} -eq 0 ]] ||
+	abort "Can't run without: $(joinBy ', ' "${missing[@]}")"
+unset missing tools required_tools
 
 # Process command line options    {{{1
 # - results in $ARGS holding remaining non-option command line arguments
 processOptions "${@}"
 
 # Check that wallpaper directories are present    {{{1
-for wp_dir in "${dir[@]}" ; do
-    [[ -d "$wp_dir" ]] || \
-        abort "Fatal: missing required wallpaper directory: $wp_dir"
+for wp_dir in "${dir[@]}"; do
+	[[ -d "$wp_dir" ]] ||
+		abort "Fatal: missing required wallpaper directory: $wp_dir"
 done
 
 # Extract monitor information    {{{1
@@ -159,42 +170,42 @@ declare -A monitor=()
 output="$(xrandr --listmonitors | grep -v "^Monitors: ")"
 old_IFS="$IFS"
 IFS=$'\n'
-lines=( $output )
+lines=("$output")
 IFS="$old_IFS"
-for line in "${lines[@]}" ; do
-    # strip leading spaces
-    line="${line#"${line%%[![:space:]]*}"}"
-    # extract monitor number as assigned by xrandr
-    number=$(cut -d':' -f1 <<<$line)
-    # extract monitor name as assigned by xrandr
-    name="$(rev <<<$line | cut -d' ' -f1 | rev)"
-    # save extracted details
-    monitor[$number]="$name"
+for line in "${lines[@]}"; do
+	# strip leading spaces
+	line="${line#"${line%%[![:space:]]*}"}"
+	# extract monitor number as assigned by xrandr
+	number=$(cut -d':' -f1 <<<"$line")
+	# extract monitor name as assigned by xrandr
+	name="$(rev <<<"$line" | cut -d' ' -f1 | rev)"
+	# save extracted details
+	monitor[$number]="$name"
 done
 count=${#monitor[@]}
 [[ $count -eq 2 ]] || abort "Fatal: expected 2 monitors, got $count"
-unset lines  name  number  old_IFS  output
+unset lines name number old_IFS output
 
 # Get wallpaper files in monitor sequence    {{{1
 # - cheat because xrandr assigns monitor numbers sequentially from 0
 # - monitor numbers are keys in associative array 'monitor'
 # - so 'seq 0 $upper' cycles through monitor numbers in sequential order
 files=()
-upper=$(( $count - 1 ))
-for key in $(seq 0 $upper) ; do
-    # get monitor name as assigned by xrandr
-    monitor_name="${monitor[$key]}"
-    # get resolution of monitor
-    monitor_resolution="${resolution[$monitor_name]}"
-    # get directory with wallpapers of that resolution
-    monitor_dir="${dir[$monitor_resolution]}"
-    # randomly select a wallpaper file from directory
-    file="$(shuf --echo --head-count=1 "$monitor_dir"/*)"
-    # save file path
-    files+=( $file )
+upper=$((count - 1))
+for key in $(seq 0 $upper); do
+	# get monitor name as assigned by xrandr
+	monitor_name="${monitor[$key]}"
+	# get resolution of monitor
+	monitor_resolution="${resolution[$monitor_name]}"
+	# get directory with wallpapers of that resolution
+	monitor_dir="${dir[$monitor_resolution]}"
+	# randomly select a wallpaper file from directory
+	file="$(shuf --echo --head-count=1 "$monitor_dir"/*)"
+	# save file path
+	files+=("$file")
 done
-unset dir  file  key  monitor  monitor_dir  monitor_name
-unset monitor_resolution  resolution  upper
+unset dir file key monitor monitor_dir monitor_name
+unset monitor_resolution resolution upper
 
 # Set monitor backgrounds    {{{1
 # - feh assigns multiple image files to monitors in monitor number sequence
diff --git a/i3/.local/bin/i3-my-get-window-criteria b/i3/.local/bin/i3-my-get-window-criteria
--- a/i3/.local/bin/i3-my-get-window-criteria
+++ b/i3/.local/bin/i3-my-get-window-criteria
@@ -6,7 +6,6 @@
 # Created: 2022-05-11
 # Credit: jottr/i3-get-window-criteria (https://gist.github.com/jottr/8645010)
 
-
 # ERROR HANDLING
 
 # Exit on error. Append "|| true" if you expect an error.
@@ -20,23 +19,21 @@ set -o pipefail
 # Turn on traces, useful while debugging but commented out by default
 # set -o xtrace
 
-
 # VARIABLES
 
-self="$(basename $0)"
+self="$(basename "$0")"
 match_int='[0-9][0-9]*'
 match_string='".*"'
-match_qstring='"[^"\\]*(\\.[^"\\]*)*"'  # adds 1 backreference
+match_qstring='"[^"\\]*(\\.[^"\\]*)*"' # adds 1 backreference
 match_class="^WM_CLASS\(STRING\) = ($match_qstring), ($match_qstring)$"
 match_role="^WM_WINDOW_ROLE\(STRING\) = ($match_qstring)$"
 match_name="^WM_NAME\(STRING\) = ($match_string)$"
 match_net_name="^_NET_WM_NAME\(UTF8_STRING\) = ($match_qstring)$"
 required_tools=(
-    getopt
-    xwininfo
-    xprop
+	getopt
+	xwininfo
+	xprop
 )
-
 
 # PROCEDURES
 
@@ -44,8 +41,8 @@ required_tools=(
 #   params: nil
 #   prints: nil
 #   return: nil
-displayUsage () {
-cat << _USAGE
+displayUsage() {
+	cat <<_USAGE
 ${self}: get window criteria for use with i3 config commands
 
 To use, run this script, then click on a window to see its
@@ -76,54 +73,64 @@ _USAGE
 #   return: nil
 #   note:   after execution variable ARGS contains
 #           remaining command line args (after options removed)
-processOptions () {
-    # read the command line options
-    local OPTIONS="$(                     \
-        getopt                            \
-            --options hvd                 \
-            --long    help,verbose,debug  \
-            --name    "${BASH_SOURCE[0]}" \
-            -- "${@}"                     \
-    )"
-    [[ ${?} -eq 0 ]] || {
-        echo 'Invalid command line options' 1>&2
-        exit 1
-    }
-    eval set -- "${OPTIONS}"
-    while true ; do
-        case "${1}" in
-        -h | --help    ) displayUsage   ; exit 0  ;;
-        -v | --verbose ) set -o verbose ; shift 1 ;;
-        -d | --debug   ) set -o xtrace  ; shift 1 ;;
-        --             ) shift ; break ;;
-        *              ) break ;;
-        esac
-    done
-    ARGS="${@}"  # remaining arguments
+processOptions() {
+	# read the command line options
+	local OPTIONS
+	if ! OPTIONS="$(
+		getopt \
+			--options hvd \
+			--long help,verbose,debug \
+			--name "${BASH_SOURCE[0]}" \
+			-- "${@}"
+	)"; then
+		echo 'Invalid command line options' 1>&2
+		exit 1
+	fi
+	eval set -- "${OPTIONS}"
+	while true; do
+		case "${1}" in
+		-h | --help)
+			displayUsage
+			exit 0
+			;;
+		-v | --verbose)
+			set -o verbose
+			shift 1
+			;;
+		-d | --debug)
+			set -o xtrace
+			shift 1
+			;;
+		--)
+			shift
+			break
+			;;
+		*) break ;;
+		esac
+	done
 }
 # Join items
 #   params: 1  - delimiter
 #           2+ - items to be joined
 #   prints: string containing joined items
 #   return: nil
-function joinBy () {
-    local d=$1
-    shift
-    local f=$1
-    shift
-    printf %s "$f" "${@/#/$d}"
+function joinBy() {
+	local d=$1
+	shift
+	local f=$1
+	shift
+	printf %s "$f" "${@/#/$d}"
 }
-
 
 # MAIN
 
 # Check for required tools
 missing=()
-for tool in "${required_tools[@]}" ; do
-    command -v "${tool}" &>/dev/null || missing+=("${tool}")
+for tool in "${required_tools[@]}"; do
+	command -v "${tool}" &>/dev/null || missing+=("${tool}")
 done
-[[ ${#missing[@]} -eq 0 ]] \
-    || dnFailScript "Can't run without: $(joinBy ', ' "${missing[@]}")"
+[[ ${#missing[@]} -eq 0 ]] ||
+	dnFailScript "Can't run without: $(joinBy ', ' "${missing[@]}")"
 unset missing tools required_tools
 
 # Process command line options
@@ -132,22 +139,24 @@ processOptions "${@}"
 
 # Get and display window criteria
 {
-    # run xwininfo, get window id
-    window_id="$(                                                 \
-        xwininfo -int |                                           \
-        sed -nre "s/^xwininfo: Window id: ($match_int) .*$/\1/p"  \
-    )"
-    echo "id=$window_id"
+	# run xwininfo, get window id
+	window_id="$(
+		xwininfo -int |
+			sed -nre "s/^xwininfo: Window id: ($match_int) .*$/\1/p"
+	)"
+	echo "id=$window_id"
 
-    # run xprop, transform its output into i3 criteria
-    # - handle fallback to WM_NAME when _NET_WM_NAME isn't set
-    xprop -id $window_id |
-        sed -nr \
-            -e "s/$match_class/instance=\1\nclass=\3/p" \
-            -e "s/$match_role/window_role=\1/p" \
-            -e "/$match_name/{s//title=\1/; h}" \
-            -e "/$match_net_name/{s//title=\1/; h}" \
-            -e '${g; p}'
+	# run xprop, transform its output into i3 criteria
+	# - handle fallback to WM_NAME when _NET_WM_NAME isn't set
+	# - shellcheck misinterprets sed command '${g; p}' as bash expression
+	# shellcheck disable=2016
+	xprop -id "$window_id" |
+		sed -nr \
+			-e "s/$match_class/instance=\1\nclass=\3/p" \
+			-e "s/$match_role/window_role=\1/p" \
+			-e "/$match_name/{s//title=\1/; h}" \
+			-e "/$match_net_name/{s//title=\1/; h}" \
+			-e '${g; p}'
 } | sort | tr "\n" " " | sed -r 's/^(.*) $/[\1]\n/'
 
 # vim:foldmethod=marker:
diff --git a/i3/.local/bin/i3-my-help b/i3/.local/bin/i3-my-help
--- a/i3/.local/bin/i3-my-help
+++ b/i3/.local/bin/i3-my-help
@@ -24,12 +24,12 @@ set -o pipefail
 self="$(basename "$0")"
 parameters=" [-v] [-d]"
 required_tools=(
-    awk
-    basename
-    column
-    getopt
-    mapfile
-    rofi
+	awk
+	basename
+	column
+	getopt
+	mapfile
+	rofi
 )
 i3_config="$HOME/.config/i3/config"
 # }}}1
@@ -40,8 +40,8 @@ i3_config="$HOME/.config/i3/config"
 #   params: nil
 #   prints: nil
 #   return: nil
-displayUsage () {
-cat << _USAGE
+displayUsage() {
+	cat <<_USAGE
 ${self}: extract and display i3 shortcuts
 
 Extracts shortcut information from the i3 config file
@@ -87,61 +87,72 @@ _USAGE
 #   return: nil
 #   note:   after execution variable ARGS contains
 #           remaining command line args (after options removed)
-processOptions () {
-    # read the command line options
-    local OPTIONS="$(                      \
-        getopt                             \
-            --options hvd:                 \
-            --long    help,verbose,debug   \
-            --name    "${BASH_SOURCE[0]}"  \
-            -- "${@}"                      \
-    )"
-    [[ ${?} -eq 0 ]] || {
-        echo 'Invalid command line options' 1>&2
-        exit 1
-    }
-    eval set -- "${OPTIONS}"
-    while true ; do
-        case "${1}" in
-        -h | --help    ) displayUsage   ; exit 0  ;;
-        -v | --verbose ) set -o verbose ; shift 1 ;;
-        -d | --debug   ) set -o xtrace  ; shift 1 ;;
-        --             ) shift ; break ;;
-        *              ) break ;;
-        esac
-    done
-    ARGS="${@}"  # remaining arguments
+processOptions() {
+	# read the command line options
+	local OPTIONS
+	if ! OPTIONS="$(
+		getopt \
+			--options hvd: \
+			--long help,verbose,debug \
+			--name "${BASH_SOURCE[0]}" \
+			-- "${@}"
+	)"; then
+		echo 'Invalid command line options' 1>&2
+		exit 1
+	fi
+	eval set -- "${OPTIONS}"
+	while true; do
+		case "${1}" in
+		-h | --help)
+			displayUsage
+			exit 0
+			;;
+		-v | --verbose)
+			set -o verbose
+			shift 1
+			;;
+		-d | --debug)
+			set -o xtrace
+			shift 1
+			;;
+		--)
+			shift
+			break
+			;;
+		*) break ;;
+		esac
+	done
 }
 # Join items    {{{1
 #   params: 1  - delimiter
 #           2+ - items to be joined
 #   prints: string containing joined items
 #   return: nil
-function joinBy () {
-    local d=$1
-    shift
-    local f=$1
-    shift
-    printf %s "$f" "${@/#/$d}"
-}    # }}}1
+function joinBy() {
+	local d=$1
+	shift
+	local f=$1
+	shift
+	printf %s "$f" "${@/#/$d}"
+} # }}}1
 
 # MAIN
 
 # Checks    {{{1
 # - for required tools
 missing=()
-for tool in "${required_tools[@]}" ; do
-    command -v "${tool}" &>/dev/null || missing+=("${tool}")
+for tool in "${required_tools[@]}"; do
+	command -v "${tool}" &>/dev/null || missing+=("${tool}")
 done
-if [[ ${#missing[@]} -ne 0 ]] ; then
-    echo "Can't run without: $(joinBy ', ' "${missing[@]}")" > /dev/stderr
-    exit 1
+if [[ ${#missing[@]} -ne 0 ]]; then
+	echo "Can't run without: $(joinBy ', ' "${missing[@]}")" >/dev/stderr
+	exit 1
 fi
 unset missing tools required_tools
 # - for i3 config file
-if [[ ! -f "$i3_config" ]] && [[ ! -h "$i3_config" ]] ; then
-    echo "Can't locate i3 config file: $i3_config" > /dev/stderr
-    exit 1
+if [[ ! -f "$i3_config" ]] && [[ ! -L "$i3_config" ]]; then
+	echo "Can't locate i3 config file: $i3_config" >/dev/stderr
+	exit 1
 fi
 
 # Process command line options    {{{1
@@ -152,11 +163,11 @@ processOptions "${@}"
 # - for i3 shortcuts $1==bindsym
 # - for non-i3 shortcuts $1==#@
 # - load into 'items' array
-mapfile                                             \
-    -t items                                        \
-    <<<"$(                                          \
-        awk                                         \
-        '                                           \
+mapfile \
+	-t items \
+	<<<"$(
+		awk \
+			'                                           \
             # process line if it begins with        \
             # <bindsym> or <#@>, and previous       \
             # line started with <##>                \
@@ -180,21 +191,21 @@ mapfile                                             \
             $1=="##" {                              \
                 for(i=2;i<=NF;i++)last=last" "$i    \
             }                                       \
-        ' "$i3_config"                              \
-    )"
+        ' "$i3_config"
+	)"
 
 # Display combined shortcuts    {{{1
 # - column: tab-separated input, table output
 # - rofi: read from stdin, resize/reposition dialog
-printf '%s\n' "${items[@]}"                \
-| column --separator $'\t'                 \
-         --table                           \
-| rofi -monitor 'primary'                  \
-       -theme-str '#window{width:20%;}'    \
-       -theme-str '#window{y-offset:40;}'  \
-       -theme-str '#listview{lines:30;}'   \
-       -dmenu                              \
-       -i
+printf '%s\n' "${items[@]}" |
+	column --separator $'\t' \
+		--table |
+	rofi -monitor 'primary' \
+		-theme-str '#window{width:20%;}' \
+		-theme-str '#window{y-offset:40;}' \
+		-theme-str '#listview{lines:30;}' \
+		-dmenu \
+		-i
 # }}}1
 
 # vim:foldmethod=marker:
diff --git a/i3/.local/bin/i3-my-screenshot b/i3/.local/bin/i3-my-screenshot
--- a/i3/.local/bin/i3-my-screenshot
+++ b/i3/.local/bin/i3-my-screenshot
@@ -22,25 +22,25 @@ set -o pipefail
 
 self="$(basename "$0")"
 required_tools=(
-    basename   kill          tee
-    cut        maim          trap
-    date       notify-send   xclip
-    feh        pidof         xrandr
-    getopt     ps            xdotool
-    grep       sed           zenity
-    i3-msg     sleep
+	basename kill tee
+	cut maim trap
+	date notify-send xclip
+	feh pidof xrandr
+	getopt ps xdotool
+	grep sed zenity
+	i3-msg sleep
 )
 to_clipboard=false
 to_file=false
-get_window=false     # window with focus
-get_region=false     # user selects region to copy
-get_screen=false     # get current screen
-get_desktop=false    # get all monitor screens
+get_window=false  # window with focus
+get_region=false  # user selects region to copy
+get_screen=false  # get current screen
+get_desktop=false # get all monitor screens
 save_name="$(date +%F_%H-%M-%S_%z).png"
-if [[ -d $HOME/Downloads ]] ; then
-    save_path="$HOME/Downloads"
+if [[ -d $HOME/Downloads ]]; then
+	save_path="$HOME/Downloads"
 else
-    save_path="$HOME"
+	save_path="$HOME"
 fi
 save_fp="$save_path/$save_name"
 # }}}1
@@ -51,8 +51,8 @@ save_fp="$save_path/$save_name"
 #   params: nil
 #   prints: nil
 #   return: nil
-displayUsage () {
-cat << _USAGE
+displayUsage() {
+	cat <<_USAGE
 ${self}: screenshot
 
 A utility for taking screenshots in i3.
@@ -120,115 +120,143 @@ _USAGE
 #   return: nil
 #   note:   after execution variable ARGS contains
 #           remaining command line args (after options removed)
-processOptions () {
-    # read the command line options
-    local LONG_OPTIONS="help,verbose,debug,clipboard,file,desktop"
-    LONG_OPTIONS="${LONG_OPTIONS},region,screen,window"
-    local OPTIONS="$(                             \
-        getopt                                    \
-            --options hvucfdrsw                   \
-            --long    $LONG_OPTIONS               \
-            --name    "${BASH_SOURCE[0]}"         \
-            -- "${@}"                             \
-    )"
-    [[ ${?} -eq 0 ]] || {
-        echo 'Invalid command line options' 1>&2
-        exit 1
-    }
-    eval set -- "${OPTIONS}"
-    while true ; do
-        case "${1}" in
-        -h | --help      ) displayUsage       ; exit 0  ;;
-        -v | --verbose   ) set -o verbose     ; shift 1 ;;
-        -u | --debug     ) set -o xtrace      ; shift 1 ;;
-        -c | --clipboard ) to_clipboard=true  ; shift 1 ;;
-        -f | --file      ) to_file=true       ; shift 1 ;;
-        -d | --desktop   ) get_desktop=true   ; shift 1 ;;
-        -r | --region    ) get_region=true    ; shift 1 ;;
-        -s | --screen    ) get_screen=true    ; shift 1 ;;
-        -w | --window    ) get_window=true    ; shift 1 ;;
-        --               ) shift ; break ;;
-        *                ) break ;;
-        esac
-    done
-    ARGS="${@}"  # remaining arguments
+processOptions() {
+	# read the command line options
+	local LONG_OPTIONS="help,verbose,debug,clipboard,file,desktop"
+	LONG_OPTIONS="${LONG_OPTIONS},region,screen,window"
+	local OPTIONS
+	if ! OPTIONS="$(
+		getopt \
+			--options hvucfdrsw \
+			--long $LONG_OPTIONS \
+			--name "${BASH_SOURCE[0]}" \
+			-- "${@}"
+	)"; then
+		echo 'Invalid command line options' 1>&2
+		exit 1
+	fi
+	eval set -- "${OPTIONS}"
+	while true; do
+		case "${1}" in
+		-h | --help)
+			displayUsage
+			exit 0
+			;;
+		-v | --verbose)
+			set -o verbose
+			shift 1
+			;;
+		-u | --debug)
+			set -o xtrace
+			shift 1
+			;;
+		-c | --clipboard)
+			to_clipboard=true
+			shift 1
+			;;
+		-f | --file)
+			to_file=true
+			shift 1
+			;;
+		-d | --desktop)
+			get_desktop=true
+			shift 1
+			;;
+		-r | --region)
+			get_region=true
+			shift 1
+			;;
+		-s | --screen)
+			get_screen=true
+			shift 1
+			;;
+		-w | --window)
+			get_window=true
+			shift 1
+			;;
+		--)
+			shift
+			break
+			;;
+		*) break ;;
+		esac
+	done
 }
 # Join items    {{{1
 #   params: 1  - delimiter
 #           2+ - items to be joined
 #   prints: string containing joined items
 #   return: nil
-function joinBy () {
-    local d=$1
-    shift
-    local f=$1
-    shift
-    printf %s "$f" "${@/#/$d}"
+function joinBy() {
+	local d=$1
+	shift
+	local f=$1
+	shift
+	printf %s "$f" "${@/#/$d}"
 }
 # Get screen geometry   {{{1
 #  params: nil
 #  prints: screen geometry
 #  return: nil
-function screen_geometry () {
-    local items
-    items=(                        \
-        $(                         \
-            xrandr --query |       \
-            grep "\bconnected\b" | \
-            sed "s/connected //" | \
-            sed "s/primary //" |   \
-            sed "s/(.*) //" |      \
-            sed "s/ x /x/"         \
-        )                          \
-    )
-    local geometry
-    geometry="$(zenity \
-        --list \
-        --text 'Select screen to capture' \
-        --print-column 2 \
-        --column 'Screen' --column 'Geometry' --column 'Size' \
-        "${items[@]}"\
-    )"
-    echo "$geometry"
+function screen_geometry() {
+	local items
+	mapfile -t items < <(
+		xrandr --query |
+			grep "\bconnected\b" |
+			sed "s/connected //" |
+			sed "s/primary //" |
+			sed "s/(.*) //" |
+			sed "s/ x /x/"
+	)
+	local geometry
+	geometry="$(
+		zenity \
+			--list \
+			--text 'Select screen to capture' \
+			--print-column 2 \
+			--column 'Screen' --column 'Geometry' --column 'Size' \
+			"${items[@]}"
+	)"
+	echo "$geometry"
 }
 # Move/rename image file    {{{1
 #  params: nil
 #  prints: nil
 #  return: nil
-move_image_file () {
-    local new_save_fp
-    new_save_fp="$(                     \
-        yad                             \
-            --file-selection            \
-            --title='Save image as'     \
-            --window-icon='filesaveas'  \
-            --file-selection            \
-            --save                      \
-            --filename="$save_fp"       \
-            --confirm-overwrite         \
-            --file-filter="*.png"       \
-    )"
-    if [[ -n "$new_save_fp" ]] && [[ "$new_save_fp" != "$save_fp" ]] ; then
-        mv --force "$save_fp" "$new_save_fp"
-    fi
+move_image_file() {
+	local new_save_fp
+	new_save_fp="$(
+		yad \
+			--file-selection \
+			--title='Save image as' \
+			--window-icon='filesaveas' \
+			--file-selection \
+			--save \
+			--filename="$save_fp" \
+			--confirm-overwrite \
+			--file-filter="*.png"
+	)"
+	if [[ -n "$new_save_fp" ]] && [[ "$new_save_fp" != "$save_fp" ]]; then
+		mv --force "$save_fp" "$new_save_fp"
+	fi
 }
 # Abort script    {{{1
 #  params: 1 - message
 #  prints: error message to console if no notify daemon
 #  return: n/a
-function abort () {
-    if command -v notify-send &>/dev/null ; then
-        notify-send                 \
-            --urgency='critical'    \
-            --expire-time=5000      \
-            --category='fatal'      \
-        'Screenshot capture failed' \
-        "$1"
-    else
-        echo 'Screenshot capture failed' > /dev/stderr
-        echo "$1" > /dev/stderr
-    fi
-    exit 1
+function abort() {
+	if command -v notify-send &>/dev/null; then
+		notify-send \
+			--urgency='critical' \
+			--expire-time=5000 \
+			--category='fatal' \
+			'Screenshot capture failed' \
+			"$1"
+	else
+		echo 'Screenshot capture failed' >/dev/stderr
+		echo "$1" >/dev/stderr
+	fi
+	exit 1
 }
 # }}}1
 
@@ -239,11 +267,11 @@ function abort () {
 # - check for required tools    {{{2
 
 missing=()
-for tool in "${required_tools[@]}" ; do
-    command -v "${tool}" &>/dev/null || missing+=("${tool}")
+for tool in "${required_tools[@]}"; do
+	command -v "${tool}" &>/dev/null || missing+=("${tool}")
 done
-[[ ${#missing[@]} -eq 0 ]] \
-    || abort "Can't run without: $(joinBy ', ' "${missing[@]}")"
+[[ ${#missing[@]} -eq 0 ]] ||
+	abort "Can't run without: $(joinBy ', ' "${missing[@]}")"
 unset missing tools required_tools
 
 # - process command line options    {{{2
@@ -254,14 +282,18 @@ processOptions "${@}"
 
 # -- check that an output argument is supplied
 count=0
-for opt in $to_clipboard $to_file ; do
-    [[ $opt = true ]] && let "count += 1"
+for opt in $to_clipboard $to_file; do
+	# ((c++)) gives error status code when going from 0 to 1
+	# shellcheck disable=2015
+	[[ $opt = true ]] && ((count++)) || true
 done
 [[ $count -eq 0 ]] && abort "Must specify destination(s)\n['-c','-f']"
 # -- check only one selection method nominated
 count=0
-for opt in $get_desktop $get_region $get_screen $get_window ; do
-    [[ $opt = true ]] && let "count += 1"
+for opt in $get_desktop $get_region $get_screen $get_window; do
+	# ((c++)) gives error status code when going from 0 to 1
+	# shellcheck disable=2015
+	[[ $opt = true ]] && ((count++)) || true
 done
 [[ $count -eq 0 ]] && abort "Must specify a selection method\n[-d,-r,-s,-w]"
 [[ $count -gt 1 ]] && abort "Specify only 1 selection method\n[-d,-r,-s,-w]"
@@ -271,72 +303,72 @@ done
 # - stop oneko if running
 oneko_cmd='oneko -time 70000 -bg red -position -30+20'
 restart_oneko=false
-if command -v oneko &>/dev/null ; then
-    oneko_path="$(command -v oneko)"
-    oneko_pids=()
-    oneko_pid=$(pidof "$oneko_path") || true
-    if [[ -n "$oneko_pid" ]] ; then
-        oneko_pids+=($oneko_pid)
-        # after i3 startup oneko has parent process '/bin/sh oneko ...'
-        while true ; do
-            ppid=$(ps -o ppid= -p $oneko_pid)
-            # result is left-padded with spaces
-            ppid="${ppid#"${ppid%%[![:space:]]*}"}"
-            if [[ $ppid > 1 ]] ; then
-                oneko_pids+=($ppid)
-                oneko_pid=$ppid
-            else
-                break
-            fi
-        done
-        restart_oneko=true
-        # kill oneko
-        kill -TERM "${oneko_pids[@]}"
-        trap "i3-msg 'exec --no-startup-id $oneko_cmd' &>/dev/null" EXIT
-    fi
+if command -v oneko &>/dev/null; then
+	oneko_path="$(command -v oneko)"
+	oneko_pids=()
+	oneko_pid=$(pidof "$oneko_path") || true
+	if [[ -n "$oneko_pid" ]]; then
+		oneko_pids+=("$oneko_pid")
+		# after i3 startup oneko has parent process '/bin/sh oneko ...'
+		while true; do
+			ppid=$(ps -o ppid= -p "$oneko_pid")
+			# result is left-padded with spaces
+			ppid="${ppid#"${ppid%%[![:space:]]*}"}"
+			if [[ $ppid -gt 1 ]]; then
+				oneko_pids+=("$ppid")
+				oneko_pid=$ppid
+			else
+				break
+			fi
+		done
+		restart_oneko=true
+		# kill oneko
+		kill -TERM "${oneko_pids[@]}"
+		trap 'i3-msg "exec --no-startup-id $oneko_cmd" &>/dev/null' EXIT
+	fi
 fi
 
 # - for window capture need to sleep
-if [[ $get_window = true ]] ; then
-    sleep 5s
+if [[ $get_window = true ]]; then
+	sleep 5s
 fi
 
 # Set capture command options based on capture type    {{{1
 # - relies on previous arg-checking to ensure only 1 capture type selected
 
-[[ $get_desktop = true ]] && opts=( )
+[[ $get_desktop = true ]] && opts=()
 
-[[ $get_region  = true ]] && opts=( --select )
+[[ $get_region = true ]] && opts=(--select)
 
-[[ $get_screen  = true ]] && opts=( --geometry=$(screen_geometry) )
+[[ $get_screen = true ]] && opts=(--geometry="$(screen_geometry)")
 
-[[ $get_window  = true ]] && opts=( --window=$(xdotool getactivewindow) )
+[[ $get_window = true ]] && opts=(--window="$(xdotool getactivewindow)")
 
 # Execute capture command depending on destination    {{{1
 # - relies on options check at startup to ensure
 #   at least 1 image destination has been selected
 
-if [[ $to_clipboard = true ]] && [[ $to_file = true ]] ; then
-    maim "${opts[@]}" | tee "$save_fp" | xclip -sel clipboard -t image/png
+if [[ $to_clipboard = true ]] && [[ $to_file = true ]]; then
+	maim "${opts[@]}" | tee "$save_fp" | xclip -sel clipboard -t image/png
 
-elif [[ $to_clipboard = true ]] ; then
-    maim "${opts[@]}" | xclip -selection clipboard -t image/png
+elif [[ $to_clipboard = true ]]; then
+	maim "${opts[@]}" | xclip -selection clipboard -t image/png
 
-elif [[ $to_file = true ]] ; then
-    maim "${opts[@]}" "$save_fp"
+elif [[ $to_file = true ]]; then
+	maim "${opts[@]}" "$save_fp"
 fi
 
 # Post-capture tasks    {{{1
 
 # - optionally move/rename destination
-if [[ $to_file = true ]] ; then
-    move_image_file
+if [[ $to_file = true ]]; then
+	move_image_file
 fi
 
 # - restart oneko if originally running
-if [[ $restart_oneko = true ]] ; then
-    i3-msg "exec --no-startup-id $oneko_cmd" &>/dev/null
-    trap - EXIT
+if [[ $restart_oneko = true ]]; then
+	i3-msg "exec --no-startup-id $oneko_cmd" &>/dev/null
+	trap - EXIT
 fi
 # }}}1
 
