use mktemp for temp file name

diff --git a/zsh/.local/bin/passfzf b/zsh/.local/bin/passfzf
--- a/zsh/.local/bin/passfzf
+++ b/zsh/.local/bin/passfzf
@@ -2,7 +2,7 @@
 # This script unlocks the pass tomb, if any, and then usess fzf to find
 # passwords and copy, show, delete, rename and duplicate them, as well as
 # to add or generate new passwords, and synchronize them (with git).
-# Dependencies: fd, fzf, pass
+# Dependencies: fd, fzf, mktemp, pass
 # Optional dependencies: git, pass-tomb
 #
 # Based on Mathieu Laparie's passfzf available from
@@ -44,6 +44,10 @@ if [[ -e "$HOME/.password.tomb" ]]; then
   "$pass" open 2>/dev/null
 fi
 
+# use temporary file
+tmpfile="$(mktemp)"
+trap '[[ -f "${tmpfile:-}" ]] && rm -rf "$tmpfile"' EXIT
+
 # select pass entry
 main() {
   #while :; do
@@ -68,25 +72,24 @@ M-<: git pull, M->: git push, C-c/C-q/Esc: clear query or exit' \
         --color='16,gutter:-1' \
         --bind="tab:down" \
         --bind="btab:up" \
-        --bind="ctrl-a:execute(echo 'add' > /tmp/passfzfarg)+print-query" \
-        --bind="ctrl-d:execute(echo 'cp' > /tmp/passfzfarg)+accept" \
-        --bind="ctrl-e:execute(echo 'edit' > /tmp/passfzfarg)+accept" \
-        --bind="ctrl-g:execute(echo 'generate --clip' > /tmp/passfzfarg)+print-query" \
-        --bind="ctrl-o:execute(echo 'otp --clip' > /tmp/passfzfarg)+accept" \
-        --bind="ctrl-r:execute(echo 'mv' > /tmp/passfzfarg)+accept" \
-        --bind="ctrl-s:execute(echo 'show' > /tmp/passfzfarg)+accept" \
-        --bind="ctrl-t:execute(echo 'rm' > /tmp/passfzfarg)+accept" \
-        --bind="alt-<:execute(echo 'git pull' > /tmp/passfzfarg)+abort" \
-        --bind="alt->:execute(echo 'git push -u --all' > /tmp/passfzfarg)+abort" \
-        --bind="enter,alt-enter:execute(echo 'show --clip' > /tmp/passfzfarg)+accept" \
-        --bind="ctrl-c,ctrl-q,esc:execute(echo 'quit' > /tmp/passfzfarg)+cancel"
+        --bind="ctrl-a:execute(echo 'add' > $tmpfile)+print-query" \
+        --bind="ctrl-d:execute(echo 'cp' > $tmpfile)+accept" \
+        --bind="ctrl-e:execute(echo 'edit' > $tmpfile)+accept" \
+        --bind="ctrl-g:execute(echo 'generate --clip' > $tmpfile)+print-query" \
+        --bind="ctrl-o:execute(echo 'otp --clip' > $tmpfile)+accept" \
+        --bind="ctrl-r:execute(echo 'mv' > $tmpfile)+accept" \
+        --bind="ctrl-s:execute(echo 'show' > $tmpfile)+accept" \
+        --bind="ctrl-t:execute(echo 'rm' > $tmpfile)+accept" \
+        --bind="alt-<:execute(echo 'git pull' > $tmpfile)+abort" \
+        --bind="alt->:execute(echo 'git push -u --all' > $tmpfile)+abort" \
+        --bind="enter,alt-enter:execute(echo 'show --clip' > $tmpfile)+accept" \
+        --bind="ctrl-c,ctrl-q,esc:execute(echo 'quit' > $tmpfile)+cancel"
   )
 
   # get user selection
-  if [[ -f "/tmp/passfzfarg" ]]; then
-    arg=$(cat /tmp/passfzfarg)
-    rm /tmp/passfzfarg
-  fi
+  arg=$(cat "$tmpfile")
+  rm "$tmpfile"
+  trap - EXIT
 
   # process selection
   if ! [[ -v "$selection" ]]; then
