execute fzf only once

diff --git a/zsh/.local/bin/passfzf b/zsh/.local/bin/passfzf
--- a/zsh/.local/bin/passfzf
+++ b/zsh/.local/bin/passfzf
@@ -41,130 +41,127 @@ fi
 
 # Select pass entry
 main() {
-  while :; do
-    clear
-    selection=$("$fd" .gpg ~/.password-store/ -d 8 |
-      "$fzf" --query "${tmp}" \
-        --prompt="# " \
-        --ansi \
-        --extended \
-        --no-border \
-        --with-nth 5.. \
-        --delimiter "/" \
-        --layout=reverse-list \
-        --no-multi \
-        --cycle \
-        --header='
+  #while :; do
+  #  clear
+  selection=$("$fd" .gpg ~/.password-store/ -d 8 |
+    "$fzf" --query "${tmp}" \
+      --prompt="# " \
+      --ansi \
+      --extended \
+      --no-border \
+      --with-nth 5.. \
+      --delimiter "/" \
+      --layout=reverse-list \
+      --no-multi \
+      --cycle \
+      --header='
 Ret: copy, C-s: show, C-e: edit, C-r: rename, C-d: duplicate, C-a: add,
 C-g: generate and copy new password, C-t: trash, C-o: copy OTP
 M-<: git pull, M->: git push, C-c/C-q/Esc: clear query or exit' \
-        --margin='1,2,1,2' \
-        --color='16,gutter:-1' \
-        --bind="tab:down" \
-        --bind="btab:up" \
-        --bind="ctrl-s:execute(echo 'show' > /tmp/passfzfarg)+accept" \
-        --bind="ctrl-e:execute(echo 'edit' > /tmp/passfzfarg)+accept" \
-        --bind="ctrl-r:execute(echo 'mv' > /tmp/passfzfarg)+accept" \
-        --bind="ctrl-d:execute(echo 'cp' > /tmp/passfzfarg)+accept" \
-        --bind="ctrl-a:execute(echo 'add' > /tmp/passfzfarg)+print-query" \
-        --bind="ctrl-g:execute(echo 'generate --clip' > /tmp/passfzfarg)+print-query" \
-        --bind="ctrl-o:execute(echo 'otp --clip' > /tmp/passfzfarg)+accept" \
-        --bind="ctrl-t:execute(echo 'rm' > /tmp/passfzfarg)+accept" \
-        --bind="alt-<:abort+execute(echo 'git pull' > /tmp/passfzfarg)" \
-        --bind="alt->:abort+execute(echo 'git push -u --all' > /tmp/passfzfarg)" \
-        --bind="ctrl-c:execute(echo 'quit' > /tmp/passfzfarg)+cancel" \
-        --bind="ctrl-q:execute(echo 'quit' > /tmp/passfzfarg)+cancel" \
-        --bind="enter:execute(echo 'show --clip' > /tmp/passfzfarg)+accept" \
-        --bind="esc:execute(echo 'quit' > /tmp/passfzfarg)+cancel")
+      --margin='1,2,1,2' \
+      --color='16,gutter:-1' \
+      --bind="tab:down" \
+      --bind="btab:up" \
+      --bind="ctrl-s:execute(echo 'show' > /tmp/passfzfarg)+accept" \
+      --bind="ctrl-e:execute(echo 'edit' > /tmp/passfzfarg)+accept" \
+      --bind="ctrl-r:execute(echo 'mv' > /tmp/passfzfarg)+accept" \
+      --bind="ctrl-d:execute(echo 'cp' > /tmp/passfzfarg)+accept" \
+      --bind="ctrl-a:execute(echo 'add' > /tmp/passfzfarg)+print-query" \
+      --bind="ctrl-g:execute(echo 'generate --clip' > /tmp/passfzfarg)+print-query" \
+      --bind="ctrl-o:execute(echo 'otp --clip' > /tmp/passfzfarg)+accept" \
+      --bind="ctrl-t:execute(echo 'rm' > /tmp/passfzfarg)+accept" \
+      --bind="alt-<:abort+execute(echo 'git pull' > /tmp/passfzfarg)" \
+      --bind="alt->:abort+execute(echo 'git push -u --all' > /tmp/passfzfarg)" \
+      --bind="ctrl-c:execute(echo 'quit' > /tmp/passfzfarg)+cancel" \
+      --bind="ctrl-q:execute(echo 'quit' > /tmp/passfzfarg)+cancel" \
+      --bind="enter:execute(echo 'show --clip' > /tmp/passfzfarg)+accept" \
+      --bind="esc:execute(echo 'quit' > /tmp/passfzfarg)+cancel")
 
-    if [[ -f "/tmp/passfzfarg" ]]; then
-      arg=$(cat /tmp/passfzfarg)
-      rm /tmp/passfzfarg
-    fi
+  if [[ -f "/tmp/passfzfarg" ]]; then
+    arg=$(cat /tmp/passfzfarg)
+    rm /tmp/passfzfarg
+  fi
 
-    if ! [[ -v "$selection" ]]; then
-      clear
-      case "$arg" in
-      add)
-        printf "\033[0;32mNew password Directory/Name:\033[0m %s" "${selection}"
+  if ! [[ -v "$selection" ]]; then
+    #clear
+    case "$arg" in
+    add)
+      printf "\033[0;32mNew password Directory/Name:\033[0m %s" "${selection}"
+      if [[ -n "$selection" ]]; then
+        printf "\033[0;32m\nPress Return to confirm or type new Directory/Name:\033[0m "
+      fi
+      read -r
+      tmp="${REPLY:=$selection}"
+      "$pass" "${arg}" "${tmp}"
+      return
+      ;;
+    cp | mv)
+      tmp=${selection%.gpg} && tmp=${tmp#"$store"}
+      printf "\033[0;32m\nNew Directory/Name to %s '%s' to:\033[0m " "${arg}" "${tmp}"
+      read -r
+      if [[ -n "$REPLY" ]]; then
+        "$pass" "${arg}" "${tmp}" "${REPLY}"
+      fi
+      return
+      ;;
+    "generate --clip")
+      printf "\033[0;32mNew password Directory/Name:\033[0m %s" "${selection}"
+      if [[ -n "$selection" ]]; then
+        printf "\033[0;32m\nPress Return to confirm or type new Directory/Name:\033[0m "
+      fi
+      read -r
+      tmp="${REPLY:=$selection}"
+      printf "\033[0;32mNumber of characters:\033[0m "
+      read -r
+      "$pass" "${arg}" --in-place "${tmp}" "${REPLY}" \
+        2>/dev/null || "$pass" "${arg}" "${tmp}" "${REPLY}"
+      #printf "\nPress any key to continue. "
+      #read -rsn1
+      return
+      ;;
+    "otp --clip")
+      if ! "$pass" otp 2>&1 | grep -q "Usage: $pass otp"; then
+        echo -e "\033[0;31mError:\033[0m the pass-otp extension not installed."
+      else
         if [[ -n "$selection" ]]; then
-          printf "\033[0;32m\nPress Return to confirm or type new Directory/Name:\033[0m "
+          tmp=${selection%.gpg} && tmp=${tmp#"$store"}
+          "$pass" otp --clip "${tmp}"
+        else
+          "$pass" otp --clip
         fi
-        read -r
-        tmp="${REPLY:=$selection}"
-        "$pass" "${arg}" "${tmp}"
-        tmp="${selection:=$tmp}"
-        continue
-        ;;
-      cp | mv)
+      fi
+      #printf "\nPress any key to continue. "
+      #read -rsn1
+      return
+      ;;
+    quit)
+      pkill -P $$
+      return
+      ;;
+    "show --clip")
+      if [[ -n "$selection" ]]; then
         tmp=${selection%.gpg} && tmp=${tmp#"$store"}
-        printf "\033[0;32m\nNew Directory/Name to %s '%s' to:\033[0m " "${arg}" "${tmp}"
-        read -r
-        if [[ -n "$REPLY" ]]; then
-          "$pass" "${arg}" "${tmp}" "${REPLY}"
-        fi
-        tmp="${REPLY:=$tmp}"
-        continue
-        ;;
-      "generate --clip")
-        printf "\033[0;32mNew password Directory/Name:\033[0m %s" "${selection}"
-        if [[ -n "$selection" ]]; then
-          printf "\033[0;32m\nPress Return to confirm or type new Directory/Name:\033[0m "
-        fi
-        read -r
-        tmp="${REPLY:=$selection}"
-        printf "\033[0;32mNumber of characters:\033[0m "
-        read -r
-        "$pass" "${arg}" --in-place "${tmp}" "${REPLY}" \
-          2>/dev/null || "$pass" "${arg}" "${tmp}" "${REPLY}"
-        tmp="${selection:=$tmp}"
-        printf "\nPress any key to continue. "
-        read -rsn1
-        continue
-        ;;
-      "otp --clip")
-        if ! "$pass" otp 2>&1 | grep -q "Usage: $pass otp"; then
-          echo -e "\033[0;31mError:\033[0m the pass-otp extension not installed."
-        else
-          if [[ -n "$selection" ]]; then
-            tmp=${selection%.gpg} && tmp=${tmp#"$store"}
-            "$pass" otp --clip "${tmp}"
-          else
-            "$pass" otp --clip
-          fi
-        fi
-        printf "\nPress any key to continue. "
-        read -rsn1
-        continue
-        ;;
-      quit)
-        pkill -P $$
-        return
-        ;;
-      "show --clip")
-        if [[ -n "$selection" ]]; then
-          tmp=${selection%.gpg} && tmp=${tmp#"$store"}
-        fi
-        "$pass" show --clip "${tmp}"
-        printf "\nPress any key to continue. "
-        read -rsn1
-        continue
-        ;;
-      *)
-        # edit|show|rm
-        if [[ -n "$selection" ]]; then
-          tmp=${selection%.gpg} && tmp=${tmp#"$store"}
-          "$pass" "${arg}" "${tmp}"
-        else
-          "$pass" "${arg}"
-        fi
-        printf "\nPress any key to continue. "
-        read -rsn1
-        continue
-        ;;
-      esac
-    fi
-  done
+      fi
+      "$pass" show --clip "${tmp}"
+      #printf "\nPress any key to continue. "
+      #read -rsn1
+      return
+      ;;
+    *)
+      # edit|show|rm
+      if [[ -n "$selection" ]]; then
+        tmp=${selection%.gpg} && tmp=${tmp#"$store"}
+        "$pass" "${arg}" "${tmp}"
+      else
+        "$pass" "${arg}"
+      fi
+      #printf "\nPress any key to continue. "
+      #read -rsn1
+      return
+      ;;
+    esac
+  fi
+  #done
 }
 
 main
@@ -176,4 +173,4 @@ if [[ -e "$HOME/.password.tomb" ]]; then
   sudo swapon -a && sudo swapon "${swapfile}" 2>/dev/null
 fi
 
-printf "\nPress any key to quit. " && read -rsn1
+#printf "\nPress any key to quit. " && read -rsn1
