replace obsolete library call

diff --git a/i3/.config/i3/bin/i3-setup-session b/i3/.config/i3/bin/i3-setup-session
--- a/i3/.config/i3/bin/i3-setup-session
+++ b/i3/.config/i3/bin/i3-setup-session
@@ -135,8 +135,10 @@ missing=()
 for tool in "${required_tools[@]}" ; do
     command -v "${tool}" &>/dev/null || missing+=("${tool}")
 done
-[[ ${#missing[@]} -eq 0 ]] \
-    || dnFailScript "Can't run without: $(joinBy ', ' "${missing[@]}")"
+if [[ ${#missing[@]} -ne 0 ]] ; then
+    echo "Can't run without: $(joinBy ', ' "${missing[@]}")" >/dev/stderr
+    exit 1
+fi
 unset missing tools required_tools
 
 # Process command line options    {{{1
